name: Test GitHub Action

on:
  push:
    branches:
      - main  # Runs when you push to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 23ds3000150@ds.study.iitm.ac.in
        run: echo "Hello, world!"
